<template>
  <div class="page"><TopBar title="تفاصيل المنتج" :showBack="true" /><main class="content">
    <template v-if="product"><img :src="product.img" :alt="product.name" class="hero"/><section class="main-info"><h2>{{ product.name }}</h2><span>{{ product.spec }}</span><strong>{{ product.price }} د.ع</strong></section><section><h3>الوصف</h3><p>{{ product.desc }}</p></section><section><h3>المواصفات</h3><div v-for="(value, key) in product.specs" :key="key" class="spec"><span>{{ key }}</span><b>{{ value }}</b></div></section><button class="add-cart" @click="add(product)"><span class="material-symbols-outlined">add_shopping_cart</span> إضافة إلى السلة</button><div class="actions"><button class="cash" @click="cashPurchase">شراء نقد</button><button class="installment" @click="buyInstallment">شراء بالقسط</button></div></template><div v-else class="empty">تعذر العثور على المنتج</div>
  </main><BottomNav active-route="/store" /></div>
</template>
<script setup>
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import TopBar from '../components/TopBar.vue'
import BottomNav from '../components/BottomNav.vue'
import { useCart } from '../composables/useCart'
const route=useRoute(), router=useRouter(); const { add }=useCart()
const products=[{name:'iPhone 16 Pro Max',spec:'256GB - تيتانيوم',price:'1,850,000',img:'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=650&fit=crop',desc:'هاتف آيفون 16 برو ماكس بسعة 256 جيجابايت، شاشة Super Retina XDR بحجم 6.9 بوصة، معالج A18 Pro، كاميرا ثلاثية 48 ميجابكسل، مقاوم للماء والغبار.',specs:{'الشاشة':'6.9 بوصة Super Retina XDR','المعالج':'A18 Pro','الذاكرة':'256GB','الكاميرا':'48MP + 12MP + 12MP','البطارية':'4685 mAh','نظام التشغيل':'iOS 18'}},{name:'Samsung S24 Ultra',spec:'512GB - أسود',price:'1,650,000',img:'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=650&fit=crop',desc:'سامسونج جالكسي S24 ألترا بسعة 512 جيجابايت، شاشة Dynamic AMOLED 2X بحجم 6.8 بوصة، معالج Snapdragon 8 Gen 3، قلم S Pen، كاميرا 200 ميجابكسل.',specs:{'الشاشة':'6.8 بوصة Dynamic AMOLED 2X','المعالج':'Snapdragon 8 Gen 3','الذاكرة':'512GB','الكاميرا':'200MP + 50MP + 12MP','البطارية':'5000 mAh','نظام التشغيل':'Android 14'}},{name:'Hisense 55 inch 4K',spec:'Smart TV - ULED',price:'820,000',img:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&h=650&fit=crop',desc:'تلفزيون هيسينس ذكي 55 بوصة بتقنية ULED 4K، دعم HDR10+، نظام تشغيل سهل الاستخدام، وصوت Dolby Atmos.',specs:{'الشاشة':'55 بوصة 4K ULED','الدقة':'3840 × 2160','HDR':'HDR10+','الصوت':'Dolby Atmos 30W','المنافذ':'3 × HDMI, 2 × USB','النظام':'VIDAA U6'}}]
const product=computed(()=>products.find(item=>item.name===route.query.name))
const cashPurchase=()=>{if(!product.value)return;const orders=JSON.parse(localStorage.getItem('golden_orders')||'[]');const total=Number(product.value.price.replace(/,/g,''));orders.push({id:orders.length?Math.max(...orders.map(order=>order.id))+1:1001,date:new Date().toLocaleDateString('ar-EG',{year:'numeric',month:'short',day:'numeric'}),status:'pending',type:'cash',products:[product.value],totalPrice:total,totalAmount:total,monthlyInstallment:total,fullName:'',phone:'',address:'',ownerNote:''});localStorage.setItem('golden_orders',JSON.stringify(orders));router.push('/orders')}
const buyInstallment=()=>product.value&&router.push('/calculator?products='+encodeURIComponent(JSON.stringify([{name:product.value.name}])))
</script>
<style scoped>.page{height:100dvh;display:flex;flex-direction:column;background:var(--bg)}.content{flex:1;overflow:auto;padding:0 16px 100px}.hero{width:calc(100% + 32px);height:270px;margin:0 -16px;object-fit:cover}.main-info{padding:18px 0 12px}.main-info h2{color:var(--on-surface);font-size:21px}.main-info span{display:block;margin-top:5px;color:var(--on-surface-variant);font-size:13px}.main-info strong{display:block;margin-top:10px;color:var(--primary);font-size:21px}section:not(.main-info){margin-top:16px;padding:15px;border:1px solid var(--outline-variant);border-radius:15px;background:var(--surface-container)}section h3{color:var(--on-surface);font-size:15px;margin-bottom:9px}section p{color:var(--on-surface-variant);font-size:13px;line-height:1.9}.spec{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--outline-variant);font-size:12px}.spec:last-child{border:0}.spec span{color:var(--on-surface-variant)}.spec b{color:var(--on-surface);text-align:left}.add-cart,.actions button{border:0;border-radius:13px;padding:14px;font:inherit;font-weight:800;cursor:pointer}.add-cart{width:100%;display:flex;justify-content:center;align-items:center;gap:7px;margin-top:16px;background:rgba(242,202,80,.14);border:1px solid rgba(242,202,80,.3);color:var(--primary)}.actions{display:flex;gap:9px;margin-top:10px}.actions button{flex:1}.cash{background:var(--surface-container-high);color:var(--on-surface)}.installment{background:var(--primary);color:#0a0f1d}.empty{padding:50px 0;text-align:center;color:var(--on-surface-variant)}</style>
